### ISSUE TITLE
Tab indexes issue

### ISSUE THREAD

**Issue by pczarn2** [DataTables/Responsive#134]
When data table is initialized with responsive extension, tab indexes are added to first column of each row to allow user to tab through rows. There is an issue when sometimes the tab indexes are not added. This can be seen on the DataTables Responsive Examples web pages, e.g. https://datatables.net/extensions/responsive/examples/initialisation/option.html Notice that tabbing through data table rows does not work UNTIL rows are re-sorted by clicking few times on any of the sort buttons. This is an issue in version 3.0.3, but we use version 2.4.0 and also see this issue on some tables (3.0.3 seems to have this issue more frequently).

**Comment by AllanJard** [comment]
`master` https://github.com/DataTables/Responsive/commit/079d776d2c7eaf9f0131b195d41da7afccc8e3dd

Thanks for pointing that error out. Fixed now.

**Comment by pczarn2** [comment]
@AllanJard Thanks for fixing it. Looks like maybe the fix wasn't applied back to the website? I still see the tabbing issue on the above mentioned web page and on the homepage of data tables (https://datatables.net/).

**Comment by pczarn2** [comment]
@AllanJard Sounds good. Let me know if you want me to test anything at that point.
